version: '3.8'
services:
  db:
    image: postgres:15
    container_name: cartera_db
    environment:
      POSTGRES_USER: donar
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: riesgo_credito
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: